Unleash/unleash-proxy

- README.md
- package-lock.json
- src/app.ts
- src/config.ts
- src/test/config.test.ts
- src/test/unleash-proxy.test.ts
> feat: add support for reverse proxies

- README.md
- example.js
- src/client.ts
- src/config.ts
- src/test/config.test.ts
Co-authored-by: mjaglewicz <michal.jaglewicz@gmail.com>
> feat: add unleash instance id option

- package-lock.json
- package.json
- src/app.ts
https://www.npmjs.com/package/compression will only compress if the threshold is met, which defaults to 1024 bytes.
> feat: add compression #23

- README.md
Addressing #25
I don't quite understand why my previous two commits are included. Please let me know if that messes it up for you, and I can try fix it.
> Add proxyPort/PORT to the list of options/env vars

- src/index.ts
Exporting the Client and createProxyConfig so the user will be able to create custom Client object and pass it to the createApp in order to be able to listen to 'ready' event as described in #46
> Export Client and createProxyConfig so the user will be able to create custom client

- package-lock.json
- package.json
- src/client.ts
- src/test/unleash.mock.ts
Call forceGetVariants over getVariants in proxy to avoid double resolution of random rollout, this is dependant on https://github.com/Unleash/unleash-client-node/pull/307
> Use forceGetVariants methods when resolving a variant

- src/app.ts
- src/config.ts
- src/server.ts
Adding options to better configure the express app powering unleash proxy. This is useful for third part integrations, e.g. Sentry (https://docs.sentry.io/platforms/node/guides/express/), which requires one hook before the handlers and one after the handlers.
This is also more in line with the unleash server, which already exposes the `preHook` option.
Closes # .
> feat: better express app configuration

- .gitignore
- src/client.ts
- src/examples/metrics.json
Count variant metrics. Proxy translates frontend SDK metrics into its own metrics and send them to Unleash backend.
In the next PR I will suggest refactored design with unleash and metrics injected into the client to make testing metrics easier.
> feat: count variant metrics

- src/app.ts
- src/client.ts
- src/create-client.ts
- src/test/client.test.ts
- src/test/create-fake-client.ts
- src/test/metrics.mock.ts
Making Unleash client testable by using dependency injection.
In a followup PR I will write actual tests for metrics since we have this option now.
> refactor: make unleash client testable

- package.json
- src/test/client.test.ts
- src/test/create-fake-client.ts
- src/test/metrics.mock.ts
- src/test/unleash.mock.ts
* added tests for metrics
* bump up the version since this change is already tested and ready to go live
* stopped fake unleash from initializing parent unleash, so we don't need to disable metrics and all open handles errors from jest are gone
This PR builds upon https://github.com/Unleash/unleash-proxy/pull/131 that made the proxy more testable
> Variant metrics prod ready

- package.json
- src/openapi/index.ts
- src/openapi/openapi-service.ts
- yarn.lock
Basepath is not part of the server URL in openapi
> Basepath in servers

- src/test/client.mock.ts
- src/test/unleash-proxy.test.ts
- src/unleash-proxy.ts
> fix: /client/features should accept client tokens configured

- .github/workflows/push-ecr-releases.yml
Switching to new ecr publish role that is managed by code.
> chore: switch docker publish role

- .github/workflows/node.js.yml
- .github/workflows/release.yml
- package.json
- src/client.ts
- src/openapi/spec/api-request-schema.ts
- src/openapi/spec/variant-schema.ts
- src/test/__snapshots__/openapi.test.ts.snap
- src/test/unleash.mock.ts
- yarn.lock
Strategy variants support by including the latest Unleash Node.js SDK version:
* fixed TS types
* switched to getVariant as forceGetVariant is not longer needed 
* new beta version of the proxy
* min Node version 16, prev it was 14
* not adding openapi docs since we're moving towards edge
> feat: strategy variants support

- package.json
- yarn.lock
> chore: version bump

- README.md
Adds a small note to the README that recommends considering using Unleash Edge instead.
> docs: add note to consider Edge instead

- package.json
- yarn.lock
* upgraded node SDK to support dependent features
* upgrading own version since new capability is available after upgrading node SDK
> feat: upgrade node sdk to support dependent features

- package.json
- yarn.lock
Upgrading Node SDK with variant hashing fix.
Also use this to upgrade proxy to version 1.0.0.
> fix: variant hashing through node sdk

- package.json
- src/context-middleware.ts
Context fallback for non GET and non POST methods
> fix: context fallback

- Dockerfile
What it says on the box.  
Closes #161
> chore: Update openssl to address a security vulnerability

- package.json
- src/client.ts
- src/openapi/spec/feature-schema.ts
- src/openapi/spec/variant-schema.ts
- src/test/__snapshots__/openapi.test.ts.snap
- src/test/unleash.mock.ts
- yarn.lock
> chore: upgrade node client

- README.md
- package.json
- yarn.lock
Support for HTTP_PROXY and HTTPS_PROXY env variables. It makes proxy work the same way as edge.
Upgrading Node SDK with the proxy support: https://github.com/Unleash/unleash-client-node/pull/638
> feat: support for http and https proxy config

- package.json
Same as https://github.com/Unleash/unleash-proxy/pull/181
> chore: bump version to v1.4.2

- README.md
Add section to docs explaining that this repository is in maintenance mode.
> docs: add maintenance mode
