Unleash/unleash-proxy

- README.md
There's an extra `docker pull` in the command 😄
> Fix typo in `docker pull` command

- README.md
- example.js
- src/config.ts
- src/test/config.test.ts
- src/test/unleash-proxy.test.ts
- src/unleash-proxy.ts
We have problem with Authorization header cause it's used for our "development gate" for jwt tokens & nginx so we have to provide custom header... I will also prepare PR for UI client sdk to provide that possibility (atm we wrapped fetch to provide custom header...) 
Kind regards
Dziczek
> feat: additional possibility to customize header for proxy secrets

- README.md
As was mentioned in the community Slack, these two env variables are not correct in the documentation. I'm not sure which version is intentional, but with the current version of the proxy, these are the values that it looks for.
> docs: fix env variable names so the docs match the implementation.

- README.md
As mentioned in #49, the description for this configuration parameter
was rather misleading. This update changes the description in an
effort to making it clearer. Suggestions are very welcome.
> docs: Fix description of `proxy_base_path` to match implementation

- README.md
- example.js
- src/client.ts
- src/config.ts
- src/test/client.mock.ts
- src/test/config.test.ts
- src/unleash-proxy.ts
Add support for the bootstrap feature, introduced in the Node.js SDK v3.11
For clarity we try to cover two use cases:
**1. Allow the Unleash-Proxy to bootstrap from "somewhere"** 
- Could be another Unleash-Proxy instance, a S3 bucket, or wherever you have a fresh feature-toggle-configuration state stored.
- expBootstrap.url - where the proxy should bootstrap from. Can also be set via `EXP_BOOTSTRAP_URL`
- expBootstrap.urlHeaders - headers to be added to the request. Typically the Authorization header.
**2. Allow any server-side SDK to bootstrap from the the Unleash Proxy.**
- The SDKs should connect to the built in "bootstrap url" and provide a `expBoostrapTokens`. These tokens needs to be different than the `clientKeys`, as the bootstrap data will be the full local cache of all feature …
> feat: experimental support for bootstrap

- package.json
- tsconfig.json
This PR outputs types to the `/dist` folder to be able to publish them to the NPM-Registry.
```
...
npm notice 202B   dist/index.d.ts                             
npm notice 889B   dist/index.js                               
npm notice 250B   dist/index.js.map                           
npm notice 786B   dist/logger.d.ts                            
npm notice 2.0kB  dist/logger.js                              
npm notice 2.0kB  dist/logger.js.map                          
npm notice 145B   dist/metrics-schema.d.ts                    
npm notice 1.2kB  dist/metrics-schema.js                      
npm notice 1.1kB  dist/metrics-schema.js.map 
...
```
Closes #53 
Note:
- The types will also be added to the Docker-Image. This is not problematic as they will be ignored by `node` on execution …
> feat: generate type output to publish them to npm

- Dockerfile
- server.sh
This commits adds a `server.sh` script that will, when
`UNLEASH_CUSTOM_STRATEGIES_FILE` is set, copy the file into
`./dist/strategies` and use that location when loading the
strategy. This removes the need to "re-bundle" `unleash-client`,
as mentioned in #29.
> Fix loading of custom strategies when using Docker

- Dockerfile
TL;DR: Adding `Tini` as init wrapper.
As per [docker-node documentation](https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals), Node.js was not designed to run as PID 1 and to handle SIGINT they recommend using `Tini`. This will allow people to use Kubernetes to proper trigger shutdowns on old deployments.
Closes # .
> feat: add tini as a init wrapper for node

- .github/stale.yml
This change adds a stale bot config that points to the org-wide config introduced in https://github.com/Unleash/.github/pull/14
> meta: add stale bot config

- src/openapi/spec/prometheus-request-response.ts
- src/test/__snapshots__/openapi.test.ts.snap
- src/unleash-proxy.ts
Responding in a Prometheus exposition format
https://prometheus.io/docs/instrumenting/exposition_formats/
To be able to monitor if the unleash-proxy is up and running from Prometheus we need an endpoint that we can scrape i.e. responds in a format conforming to Prometheus exposition format.
Closes # .
This simple solution will suffice for us. Hopefully it can be built on further if you want more metrics.
I did not expose any other internal metrics. Did not know your policy on that or if you would like to use any other library for that in that case.
> Add Prometheus endpoint

- package.json
- src/app.ts
- src/client.ts
- src/openapi/common-responses.ts
- src/openapi/openapi-service.ts
- src/openapi/spec/lookup-toggles-schema.ts
- src/openapi/spec/unleash-context-schema.ts
- src/test/__snapshots__/openapi.test.ts.snap
- src/test/client.test.ts
- src/test/unleash-proxy.test.ts
- src/unleash-proxy.ts
This PR fixes the bug report referenced later in this text. In short, there were two things: 
1. The OpenAPI spec said the /proxy POST endpoint had a `toggleNames` property, but it's actually just `toggles`
2. If you POST invalid (according to the spec) JSON to the /proxy endpoint, then you get a 404.
These two issues have been addressed as follows:
1. The OpenAPI spec has been changed to list the property as `toggles`.
2. POSTing invalid data (that can't be parsed) now results in a 400. Posting valid json that doesn't conform to what we expect yields a 200. The decision for the latter is that there's been tests for this for a long time, so it's the expected behavior.
The root cause of the 404 bug was that the OpenAPI validator required `toggleNames`. Further, the error handler that takes …
> fix: OpenAPI POST /features payload is wrong

- src/openapi/common-responses.ts
- src/openapi/openapi-service.ts
- src/openapi/spec/api-request-response.ts
- src/test/__snapshots__/openapi.test.ts.snap
- src/unleash-proxy.ts
This change explicitly documents the 500 errors that can happen for GET and POST requests to the /proxy endpoint. When this happens it's most likely a result of a custom strategy throwing an exception (see #79).
As a bonus, it also fixes the description of the /proxy/client/features endpoint.
> docs: document 500 errors in OpenAPI

- src/client.ts
- src/config.ts
- src/test/config.test.ts
Allows adding in httpOptions which then gets passed to the unleash client.
This enables
- Using self-signed certs (successfully tested with GitLab) 
It should be setup that if the user doesn't add a custom httpOptions it would maintain the same runtime before this merge request. 
Let me know if changes need to be made! I tried to minimize the changes best I could. :) 
Closes # .
src/client.ts
src/config.ts
Just want to make sure this isn't a breaking change or if that is the right place to add in the config object.
> Allow user to add httpOptions in the config

- example.js
- src/openapi/index.ts
- src/openapi/spec/register-client-request.ts
- src/openapi/spec/register-client-schema.ts
- src/test/__snapshots__/openapi.test.ts.snap
- src/test/unleash-proxy.test.ts
- src/unleash-proxy.ts
The Unleash proxy has experimental support for server-side SDKs. There was one limitation currently where the proxy does not handle the /client/register call, and thus yields a 404 for these requests, causing a lot of noise in the applications using a serverside SDK. 
This PR adds support for the request (but disregards the registrations, until Unleash supports a "connect via" registration message.
> fix: should not yield 404 when serverside SDK tries to register

- README.md
It seems `UNLEASH_PROXY_SECRETS` is deprecated and we should have `UNLEASH_PROXY_CLIENT_KEYS` in our examples instead.
> Remove deprecated configuration option

- .github/workflows/push-ecr-releases.yml
This PR adds a workflow that should build ARM64 and AMD64 images of proxy and push them to our Public ECR repository.
I've added a AWS key/secret pair to secrets which should allow the action to run. Kinda want to try on more flows than just tag, to see that it works, maybe push to main as well until we've confirmed it works?
> Updated to publish released tags to ECR as well as docker hub

- package.json
- src/test/__snapshots__/openapi.test.ts.snap
- yarn.lock
This upgrades to the beta release of express-openapi which solves a problem with Content Security Policy (CSP)
> chore: upgrade @unleash/express-openapi

- package.json
This prepares the release for OpenAPI fixing the issue with Content Security Policy about executing an inline script (https://content-security-policy.com/examples/allow-inline-script/)
> chore: bump version v0.10.4

- .github/workflows/push-ecr-releases.yml
So, releasing to ecr-public failed with region missing, this seems to be since we forgot to add registry-type. This PR adds registry-type to the login action
> fix: add registry-type to login action

- src/config.ts
- src/test/config.test.ts
Currently, we cannot fully customize the CORS options through environment variables (only `origin` and `maxAge` are customizable) which is specially useful when running Unleash Proxy through Docker.
The reason I got to this is that I need to pass `Access-Control-Allow-Credentials` as `true` along with a specific `Access-Control-Allow-Origin` value rather than just `*`, otherwise you get [this error](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials).
To get around this I had to use NGINX as a proxy for Unleash Proxy to change the HTTP headers on the fly, which is weird and an unnecessary overhead as it's basically a proxy for a proxy, so this PR aims to allow customizing all the [CORS  options](https://github.com/expressjs/cors#configuration-options …
> feat(cors): allow specifying all CORS options through env vars

- package.json
- src/config.ts
- src/test/config.test.ts
- yarn.lock
As requested in #76. The proxy should just be smart enough to format proxyBasePath to the format we expect (That is, leading slash and no trailing slash) This PR sanitizes when creating the config object.
> sanitize proxy base path

- .github/workflows/release_changelog.yml
To avoid flagging alphas and betas as actual releases, 
this PR uses the prerelease flag when github.ref contains beta or alpha
> Updated workflow to flag as prerelease

- README.md
- example.js
- src/test/unleash-proxy.test.ts
- src/unleash-proxy.ts
This PR extends the POST endpoint for fetching feature toggle configurations to also support empty list of feature toggle names, which basically makes POST work the same way as a regular GET request. 
```
POST https://url/proxy
body: {"context": "{"appName": "test"}}
```
Needed for https://github.com/Unleash/unleash-proxy-client-js/pull/125
> feat: support regular evaluations via POST

- package.json
- src/openapi/openapi-helpers.ts
- src/openapi/spec/unleash-context-schema.ts
- src/test/__snapshots__/openapi.test.ts.snap
- src/test/openapi.test.ts
- yarn.lock
This fix will simplify converting OAS 3.0 to Swagger 2.0 conversion.
> fix: ease on the open-api specification for context properties

- src/test/__snapshots__/openapi.test.ts.snap
- src/unleash-proxy.ts
This change updates the operation description for the `POST /proxy` operation. It changes it from implying that only some toggles are returned to explicitly saying that all toggles are returned.
The original description was misleading. Probably because the author (me 🙋) didn't quite understand how the endpoint worked when they wrote it.
> docs: fix endpoint description POST /proxy

- src/test/__snapshots__/openapi.test.ts.snap
- src/unleash-proxy.ts
This change updates the description of POST `/proxy` and `/proxy/all` and GET `/proxy/all`
It states clearly what happens if you don't provide the optional `toggles` part of the request payload.
It also removes what appears to be copy-paste errors that have been left in.
Because the information contained within this new bit of documentation was unknown to me and confusing when I came across it.
> docs: Update openapi descriptions for post endpoints (and get all)

- src/test/__snapshots__/openapi.test.ts.snap
- src/unleash-proxy.ts
As suggested by @gastonfournier, these changes make the proxy's openapi docs a little better.
Builds upon #118
> docs: further openapi doc clarifications

- src/context-middleware.ts
- src/test/unleash-proxy.test.ts
- src/unleash-proxy.ts
This cleanup aims to reduce duplication in the main controller of the proxy by using middlewares for two things:
1. Validate proxy is ready to handle requests
2. Resolve the context (and enrich it with custom enrichers)
/cc @LukasHeimann
> fix: cleanup controller

- src/app.ts
Solves problem introduced in https://github.com/Unleash/unleash-proxy/pull/119
If application in general supports other content types (file upload for example) then now it doesn't. Moving required types checking to proxy endpoints resolves problem/limitation
> fix: move required content type check

- .github/workflows/push-ecr-releases.yml
So. ecr-public can only be logged in to from us-east-1, so this PR sets the region of the login task to be us-east-1. This is part of publishing unleash-proxy to AWS ECR public.
> fix: define region to ensure we login to us-east-1 for public

- package.json
This PR releases v0.15.2. It contains a bugfix (#126) for the recently released content-type checking that the proxy does.
Prior to this fix, the content-type checking would apply to all endpoints on the app you use for the proxy. If you use the proxy as a standalone app, then that doesn't really matter, but if you pass in a separate app, then all non-proxy endpoints will also have the content-type checking applied.
The fix, provided by @Dzixxx, makes it so that the content-type validation only happens on the endpoints bundled by the proxy.
> Release v0.15.2

- src/openapi/index.ts
- src/openapi/openapi-service.ts
This PR changes the `server` property of the OpenAPI spec that we serve to make it work when you provide a proxy base path.
The way we have the spec set up, we'll only ever have a single server, so there's no point in providing the base url the way we used to. According to the [OpenAPI spec](https://swagger.io/docs/specification/api-host-and-base-path/), an empty list will make it fall back to the default, which is `/`.
The only difference you'll see in the UI from before is that the servers dropdown is gone.
Ideally, I think we would like the `/base/path` to be part of the server base path and not a prefix to each and every API endpoint. However, as we have seen in Unleash (https://github.com/Unleash/unleash/pull/2079), that isn't trivial.
This PR should fix the problem for now. If we …
> fix: make the swagger UI work correctly when using PROXY_BASE_PATH

- Dockerfile
This updates Node in the Dockerfile from v14 to v18, as v14 reached EOL on April 30th 2023.
v18 was selected as it is now the minimum version supported by Unleash v5.
> Update Node version in Dockerfile: v14 -> v18

- package.json
- src/client.ts
- yarn.lock
forceGetVariant in node is fixed now so we can use it. We can use strategy variants without emitting impression events inside the proxy. Events emission should be done in the frontend SDKs
> fix: force get variant uses strategy variants

- src/client.ts
What problem are we solving?
* enabled info and variant info in the same feature have to be consistent when stickiness is set to default
* also we want to have consistency between parent and child features 
Solution:
* if the user didn't provide sessionId, generate one one the fly
Is Math.random() good enough?
> feat: default session id

- src/create-context.ts
- src/test/__snapshots__/openapi.test.ts.snap
- src/test/create-context.test.ts
- src/unleash-proxy.ts
This adds the current time property to the context enricher and uses that property during the calculation for feature toggles. 
Invalid and/or missing dates fallback to undefined to keep the logical flow consistent with SDKs
> feat: proxy now respects incoming currentTime property

- src/test/create-context.test.ts
- src/test/unleash-proxy.test.ts
This is in relation to the Edge implementation. Everything this PR does is to assert how we handle something today, so that we can rely on it not changing in the future.
> test: add test cases to assert certain behavior

- Dockerfile
- package.json
- src/openapi/openapi-types.ts
- yarn.lock
Steps taken:
- Run yarn audit - reports 0 vulnerabilities (kind-of seems to be a transitive dep that is not reported here)
- Modified the docker file to update all apk packages to latest version - this solve CVE-2024-2511 by updating openssl to 3.1.4-r6
Closes #172
> chore: upgrading all apk packages to solve CVE-2024-2511

- src/test/__snapshots__/openapi.test.ts.snap
- src/test/unleash-proxy.test.ts
- src/unleash-proxy.ts
fixes https://github.com/Unleash/unleash-android-proxy-sdk/issues/77
> fix: allow clients to send metrics when using all path

- README.md
- package.json
- src/config.ts
- src/create-client.ts
- yarn.lock
https://linear.app/unleash/issue/2-2406/bump-node-sdk-in-unleash-proxy
Bumps `unleash-client` to v6, no longer passing down the `instanceId` and deprecating this property in the proxy.
> chore: bump unleash-client to v6 and deprecate unleashInstanceId

- README.md
- package.json
- src/config.ts
- src/create-client.ts
- yarn.lock
https://linear.app/unleash/issue/2-2431/revert-autogenned-instance-id-proxy
Reverts: https://github.com/Unleash/unleash-proxy/pull/180 and bumps `unleash-client` to `v6.1.0`.
Also bumps the proxy version to `1.4.3` so we can make a new release from main after merging and avoid a PR like https://github.com/Unleash/unleash-proxy/pull/183
> chore: revert deprecate instanceid (#180), unleash client 6.1.0

- package.json
- yarn.lock
https://linear.app/unleash/issue/2-2468/fix-trim-is-not-a-function-edge-case-on-context-value
Bumps `unleash-client` to `v6.1.1` and prepares for a `v1.4.4` Unleash Proxy release.
Related issue: https://github.com/Unleash/unleash-proxy/issues/185
> chore: bump unleash-client to v6.1.1

- README.md
- package.json
- src/client.ts
- src/prom-metrics/createCounter.ts
- src/prom-metrics/createGauge.ts
- src/prom-metrics/index.ts
- src/test/__snapshots__/openapi.test.ts.snap
- src/unleash-proxy.ts
- yarn.lock
Adds prometheus gauges for when we last fetched (no matter if 200 or 304) and when we last updated (only updated when status==200)
Fixes: #187
> feat: add last fetch and last update

- package.json
- yarn.lock
This updates the express dependency to 4.21.0, which fixes:
- BDSA-2024-6187
- BDSA-2024-6188
- BDSA-2024-6183
> chore: update express dependency to 4.21.0

- package.json
- src/index.ts
- src/openapi/openapi-service.ts
- src/types/openapi.d.ts
- yarn.lock
This is the work done in #195, just keeping strict: true, and updating our type definitions to reflect upstream openapi
Co-Authored-By: skyd0me
> chore: bump to upstream version of openapi

- biome.json
- package.json
- yarn.lock
#196 pointed out that we got hit by https://github.com/advisories/GHSA-pxg6-pf52-xh8x
> task: resolve cookie to 1.0.0 release

- README.md
A prospect reported that the link to Unleash Edge inside the 'Note' highlight is leading to the wrong place. However, I think we can remove this section altogether now that we have a maintenance mode notice at the top.
> Remove duplicate Edge note 
